### ISSUE TITLE
DiscordSRV prevents xAntiAFK placeholders from parsing

### ISSUE THREAD

**Issue by ChipWolf** [DiscordSRV/DiscordSRV#1041]
We discovered that adding DiscordSRV [Build-1.21.3] to our [1.16.5-R0.1-SNAPSHOT/git-Paper-526] server prevents xAntiAFK's placeholders from being parsed by PAPI.
Validated with `/papi parse` and causes issue architectsmp/k8s-gitops#106
c.c @bloodycoffin

**Comment by Vankka** [comment]
I checked this through and what I believe probably happened you `/papi reload`ed and that causes `xAntiAFK`'s expansion to stop working because it hasn't set `persist()` to return `true`. And when you were testing removing DiscordSRV you *probably* restarted the server, which would've re-enabled the xAntiAFK expansion. Either way I don't see how this is DiscordSRV related at all

**Comment by ChipWolf** [comment]
That may be why we didn't catch this `/papi reload` is in the startup script

**Comment by ChipWolf** [comment]
We've been scratching our heads over this for the evening & it turned out to be that simple; thanks @Vankka
