### ISSUE TITLE
Make discord formatting compatible in-game and vice versa

### ISSUE THREAD

**Issue by Jacketylon** [DiscordSRV/DiscordSRV#1241]
I, for one, am on a server that has a "policy" where you have to spoiler things in your message that most people probably don't want to see. This would be stuff like gory and otherwise uncomfortable topics in general. 

However, since the plugin doesn't actually display the discord message format in-game, the spoilered text is open for the whole in-game server to see whether they want to or not. So my suggestion is to somehow convert the ||spoilered|| stuff into &kspoilered&r stuff or even just ███████ stuff in-game. I know you can't interact with a message in-game to reveal the spoiler, but they don't have to be able to reveal the spoiler in-game. They can alt+tab to discord if they really want to see the spoilered text.

This can also be extended to other formatting stuff like italics and bold and strikethrough text, etc etc.

**Comment by Digifox03** [comment]
To format discord spoiler messages in minecraft the censored part should be replaced with a series of full blocks which can then be interacted in one or both of the following:
1. When hovered, the censored part is shown within a tooltip.
2. When clicked, the message is repeated in chat with the censored part visible.

I think the first option is preferable since it doesn't require any state.

**Comment by Scarsz** [comment]
Already possible with [Experiment_MCDiscordReserializer_ToDiscord](https://config.discordsrv.com/config/Experiment_MCDiscordReserializer_ToDiscord) and [Experiment_MCDiscordReserializer_ToMinecraft](https://config.discordsrv.com/config/Experiment_MCDiscordReserializer_ToMinecraft)
