### ISSUE TITLE
Reduce the size of the update message

### ISSUE THREAD

**Issue by andrewkm** [DiscordSRV/DiscordSRV#1379]
### Why?

A 5 lined warning for every commit is over the top...

```
[13:36:43] [pool-125-thread-1/WARN]: [DiscordSRV] 

The current build of DiscordSRV is outdated by 3 commits! Get the latest build at your favorite distribution center.

Spigot: https://www.spigotmc.org/resources/discordsrv.18494/
Github: https://github.com/DiscordSRV/DiscordSRV/releases
Direct Download: https://get.discordsrv.com
```

### What and How?

Config option.
Just as pretty much all other plugins do with update checkers.

### Are there alternatives?

Config option.
Just as pretty much all other plugins do with update checkers.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Vankka** [comment]
> for every commit

The extended version of the message is only logged when the version is behind older than the current release. For development builds this is reduced to a single line `This build of DiscordSRV is ahead of master but behind develop. Update your development build!`. The message might've made it seem as if it was for every commit, when it isn't.

> this option should be presented to users by default

Disabling the update checker also disables the security check that ensures the DiscordSRV version is safe to use, this is in place in case a severe security vulnerability were to be discovered. The option isn't in the config for this reason, since *unfortunately* there are lots of users who don't read comments and would blindly disable it. The option is listed on the plugin's resource page and documentation, with a disclaimer about the security implications for those that do want to take the risk.

Prehaps splitting out the update reminder & security check into different options would be wise, then the update reminder option would be safer to include in the default config.

> A 5 lined warning is over the top...

Fair argument, that message could easily be smaller than it is.

**Comment by andrewkm** [comment]
> The extended version of the message is only logged when the version is behind older than the current release. For development builds this is reduced to a single line `This build of DiscordSRV is ahead of master but behind develop. Update your development build!`. The message might've made it seem as if it was for every commit, when it isn't.

I'm getting the long message right now on the development branch, due to it being behind master by 2 commits (https://github.com/DiscordSRV/DiscordSRV/commit/e1f7a1d79474d852f2fc477c06ff9d684939c557, https://github.com/DiscordSRV/DiscordSRV/commit/339e5e81da67cfe6210679af775eb66a9b5033be)

Currently building on: https://github.com/DiscordSRV/DiscordSRV/commit/3f1478f2264f0a32917fc5b683ed3ed55ce55988

**Comment by Vankka** [comment]
> I'm getting the long message right now on the development branch, due to it being behind master by 2 commits

I'm usually the one to bump version + merge in the automated commits, but I wasn't around at the time of this update so I guess nobody did it. Resolved with https://github.com/DiscordSRV/DiscordSRV/commit/227b27568fbf3b9ffff5ee949d1c445d8c2c751f

Didn't come to mind that the updater would trigger due to that, there's definitely some room for workflow improvements here
