### ISSUE TITLE
Simple voice chat integration

### ISSUE THREAD

**Issue by DaCosySheeep** [DiscordSRV/DiscordSRV#1688]
### Why?

This feature would allow users using the discord proximity chat to talk with users using simple voice chat and vice versa

### What and How?

This would be done by the bot joining the voice channel to send the audio for all the users that are talking. The bot would also be able to listen to the audio in the voice channel to broadcast to simple voice chat.

### Are there alternatives?

If you are unwilling to implement this, would it be possible using the discordsrv api? Also this could wait for ascension as attention is directed there.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Vankka** [comment]
- Discord's API doesn't officially support receiving audio (https://github.com/discord-jda/JDA/issues/904)
- The bot can only be in one channel
  + Every Discord user in range of any Simple Voice Chat user would need to be grouped into the same Discord channel

Discord really really isn't suited for what the voice module is doing, solutions such as [OpenAudioMC](https://openaudiomc.net/) (browser based) or client-side mods such as Simple Voice Chat are much better suited to the task. I'd encourage you to try and make those work instead of any Discord based solution as those will result in a much better experience.

Phew, I rambled on a bit there

**Comment by DaCosySheeep** [comment]
The only reason I was hoping for this feature is for geyser players. I currently use simple voice chat and haven't looked at discordsrv's proximity chat. Are there any ways for bedrock players to connect to simple voice chat? Perhaps similar to the browser based one you linked above. 

I didn't realize that discord bots could only be connected to one voice channel at a time. I am assuming you mean one voice channel per server as I have seen other bots that can use voice channels such as mee6 which wouldn't work very well if they could only run in one voice channel at a time.

**Comment by Vankka** [comment]
> I am assuming you mean one voice channel per server

Yes, I ommited that as using multiple Discord servers for proximity voice is unrealistic as the bot can't move users between servers

> Are there any ways for bedrock players to connect to simple voice chat? Perhaps similar to the browser based one you linked above.

I don't know, I just know the alternatives exist and work much better than what Discord is capable of

**Comment by thewilloftheshadow** [comment]
OpenAudioMC is definitely what you're looking for if you want to provide it to Geyser players as well and don't want to use the existing DiscordSRV voice module
