### ISSUE TITLE
Fake join/quit methods for vanish plugins to use

### ISSUE THREAD

**Issue by Scarsz** [DiscordSRV/DiscordSRV#220]

**Comment by Piefanatic555** [comment]
+1 and bump for SuperVanish fake join/quit messages support

**Comment by DonSensiLeone** [comment]
yes please add support for SuperVanish , this would be awesome !

**Comment by Vankka** [comment]
This has been added. However this does not mean there are any integrated fake join/leave messages. The methods are `DiscordSRV#setJoinMessage` and `DiscordSRV#sendQuitMessage` (DiscordSRV can be accessed via `DiscordSRV#getPlugin`)

As it seems SuperVanish was requested, but it doesn't provide events for fake join/leaves, either SuperVanish needs to add in events for it or just add integration with DiscordSRV to send fake join/leave messages. Closing this issue since it only covers the API methods for this to be possible
