### ISSUE TITLE
Configure list of Discord users to ping for watchdog alert

### ISSUE THREAD

**Issue by EbonJaeger** [DiscordSRV/DiscordSRV#297]
Hello,

It would be helpful to be able to configure who get's pinged in Discord when the watchdog sends its alerts. For instance, in my case, the owner of the Discord who does get pinged isn't necessarily the person who deals with all the technical stuff like this (which would be me). For other cases, it could be that there are multiple people in the Discord who could deal with the issue, and it would be nice to have the ability to ping all of them (whether via Role or user).

**Comment by Scarsz** [comment]
A better idea would be to fix the cause of the lag in the first place

**Comment by Gnat008** [comment]
Yeah about that: it doesn't seem to exist; the watchdog has given us three false positives so far. Regardless, that doesn't make this any less of a valid suggestion.

**Comment by Scarsz** [comment]
The thing about the watchdog is that it’s impossible for a false positive to occur. It doesn’t rely on some special hack to detect lag, it looks at the last time your server completed a game tick.

**Comment by Gnat008** [comment]
Dunno what to tell ya. Either way, that's all irrelevant to this issue.

**Comment by Scarsz** [comment]
https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/resources/messages/en.yml#L198-L199

**Comment by SpaghettiSkateboard** [comment]
Came in three years later to tell you it's still giving false positives. You should probably stop giving irrelevant passive aggressive comments when someone suggests a useful feature and work on fixing your junk. :)

**Comment by Scarsz** [comment]
> Came in three years later to tell you it's still giving false positives. You should probably stop giving irrelevant passive aggressive comments when someone suggests a useful feature and work on fixing your junk. :)

Maybe work on fixing your attitude instead.

Provide factual proof that there is something wrong with the watchdog feature. Provide steps to reproduce your issue. Find the part of the code that's an issue. Otherwise, this isn't actionable whatsoever. Nobody else has reported there being an issue with the watchdog having false positives. It's much more likely that there's something wrong with your environment.

The watchdog uses the server's last tick time to know when there's an issue. The server is responsible for telling DiscordSRV's watchdog task every time it ticks. If DiscordSRV isn't informed of a tick, that's not a problem with DiscordSRV. Though, I highly doubt that's happening considering an issue with the scheduler would be much larger than a watchdog feature not working in a single plugin.
