### ISSUE TITLE
Silent Join and quit permission remove

### ISSUE THREAD

**Issue by Victor75007** [DiscordSRV/DiscordSRV#439]
Hello

I look, have permission for silent join ad quit.
But.
I have an OP, but i don't want silent join and quit.
How can i remove this "permission" , because Automatically adds to the OP.
i not added this.
I tried removed this permission with pex but not works.
I no want remove the op. 
This problem have in the lobby only.
The message works on another server even if I'm an Op or i'm in vanish.

Can you help me?
Have a nice day.

Best regards,
Victor

**Comment by Vankka** [comment]
permissions plugin's problem, not DiscordSRV's. PEX is unmaintained, have a look at LuckPerms

**Comment by Androkai** [comment]
For PEX the permission order is really important. Take a look at this: "[When I join/quit my server, a message isn't sent in the chat channel for me. What gives?](https://github.com/DiscordSRV/DiscordSRV/wiki/FAQ#when-i-joinquit-my-server-a-message-isnt-sent-in-the-chat-channel-for-me-what-gives)"

Sadly the way PEX handles OP sometimes is frustrating so like Vankka said, switching to [LuckPerms](https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/) is the best option because it's still actively maintained and the system how permissions are handled is much more mature.
