### ISSUE TITLE
Feature request: better webhooks

### ISSUE THREAD

**Issue by zeuzi** [DiscordSRV/DiscordSRV#455]
also add webhooks for the rest not only for the minecraft to discord messages
so for example the start/shut messages etc also get sent by a webhook so we dont need more bots on the server.
For the linking use the mc channel with a link command in discord

**Comment by Vankka** [comment]
Discord only has incoming webhooks, DiscordSRV also depends on a bot for other reasons like the topic updater. Thus it requires a bot.

**Comment by zeuzi** [comment]
Listen I dont care about having a bot all im saying is i dont want 10 bots on my server so i would be happy to use the bot token of my main bot and use webhooks for everything, 
the topic updates can do the main bot since it only shows the bot name for that in audit logs.

**Comment by Scarsz** [comment]
DiscordSRV requires it's own bot because of rate limits.

**Comment by zeuzi** [comment]
I dont really see a problem with this just let it be in the configs so just two new options so if anyone has problems with rate limits:
everything sent in discord as webhooks: true / false
webhook url: (url)
I dont see the issue with rate limits IF you have the setting how we use it, 
we update topic only every 5 min, also there's not much else that take's much rate limiting

**Comment by Scarsz** [comment]
There are **many** things in DiscordSRV that affect it's rate limit quota. It needs its own bot. More things are going to be moved to *embeds* with the next major version. DiscordSRV is going to need it's own bot and always will be. If you can't handle that, don't use my plugin and anyone else's for the matter because they all need a bot to do anything more advanced than just sending messages.
