### ISSUE TITLE
Suggestion: The ability to mention users

### ISSUE THREAD

**Issue by OoLunar** [DiscordSRV/DiscordSRV#510]
As mentioned in the title, the ability to mention a Discord user from the Minecraft chat would be awesome. If there are two Discord users with the same name, this can be solved by ``/minecraft:tellraw [player]`` from the console listing the Discord usernames and tags. Optionally, if someone has the Discord username and tag at hand, they can just type it in. For reference:

![2019-07-18_21 47 15](https://user-images.githubusercontent.com/46751150/61505811-b4d3fb00-a9a5-11e9-8e35-a9d984944e86.png)

**Comment by Androkai** [comment]
Thx for you request. It should already be possible to mention a Discord user by using @ + username in the ingame chat. At least without a chat plugin that might interfere with it. For multiple Discord users with the same name you just append the #1234 part. An ingame help for selecting a full Discord user name might be helpful but im not quite sure if it's already possible to implement a nice solution because selecting the name after sending the message is a bit to late for my taste, I would prefer a solution wich works like command completion but for Discord user names. It will depend on if somebody find the time to research and implement this if possible.

**Comment by OoLunar** [comment]
If I knew how to program in Java, I would help, however I specialize in PHP and C#. As of right now, the only chat plugins I have is just Essentials, and I don't think it interrupts anything. However knowing that the feature is there is comforting. Have a nice day!
