### ISSUE TITLE
Per player on/off switch

### ISSUE THREAD

**Issue by judelhaye** [DiscordSRV/DiscordSRV#550]
The idea here is to allow each player to optin to the feature with something like a /discordforward <on/off> command that would allow them to explicitly accept to forward messages to discord.

Players are not always aware that when they send a message throught the IG chat, they are forwarded to discord servers. Giving them the ability to choose if and/or when they want their messages to be forwarded would grant them a much better privacy control. 

Use cases : 
- European player impacted by the GDPR law which don't want to see their messages on US servers
- Drunk guys playing after midnight which don't want their messages to be seen by others than the actually connected buddys on the server.

**Comment by Vankka** [comment]
Doable, those use cases are pretty far fetched though.

**Comment by pkrok01** [comment]
If this feature gets implemented, a message should pop up either on their first message or when they first join stating that their messages are being relayed to Discord

**Comment by mll0** [comment]
> Doable, those use cases are pretty far fetched though.

Not that much, I know of a certain MC server where both cases evoked by the OP apply

> If this feature gets implemented, a message should pop up either on their first message or when they first join stating that their messages are being relayed to Discord

Or the state should be off by default (actually, either your proposal or mine should be an admin's choice)

**Comment by Scarsz** [comment]
> European player impacted by the GDPR law which don't want to see their messages on US servers

This isn't in the scope of DiscordSRV. DiscordSRV is just a chat bridge. Set up a message through a "first join info" plugin saying that their messages are being relayed if GDPR is something you're concerned with.

> Drunk guys playing after midnight which don't want their messages to be seen by others than the actually connected buddys on the server.

That's a pretty... odd example. Either way, I have mixed feelings about a toggle because it messes with the consistency of chat. If two people are chatting on the Minecraft server and someone has their relaying toggled, only one person's chat is going to Discord. It's going to look like they're talking to themselves; it would be silly to see. 

Also, how is this going to work for people who have channels that are dedicated to staff? Many people use DiscordSRV in a one-directional way, such that the chat channel is off limits to anyone but staff. They can then use this as a very convenient, easily searchable chat log for the server. That completely defeats the entire purpose of the plugin for these users if people can just chose to not have the messages sent.

This is of course debatable, but if you're *really* worried about people seeing what you're saying on Discord but not on Minecraft, should you really be chatting at all?
