### ISSUE TITLE
Mention specific user/role when a specific console message is sent

### ISSUE THREAD

**Issue by Collin-M** [DiscordSRV/DiscordSRV#592]
I would like to see a feature of DiscordSRV where we can customize an alert to be sent to Discord with a tag (I.E. @Administrator ALERT: <log message>).

The specific alert should be able to be customized with regex matching or at bare minimum by matching a specific prefix of the log message.

Example: When a player moves too quickly:
[Fri, 13. Dec 2019 WARN] player moved too quickly!  xxx, xxx, xxx
would be
[Fri, 13. Dec 2019 WARN] @Administrator ALERT! player moved too quickly!  xxx, xxx, xxx

Example: When server is lagging:
[Fri, 13. Dec 2019 WARN] Can't keep up! Is the server overloaded? Running 5034ms or 100 ticks behind
would be
[Fri, 13. Dec 2019 WARN] @Administrator ALERT! Can't keep up! Is the server overloaded? Running 5034ms or 100 ticks behind

**Comment by TheFALSEGamer4** [comment]
You can already so this by the way, if you have ever worked with discord webhooks its the same way. you have to do:
`<&ROLE_ID>`
To get the role id you can run:
`\@ROLE_NAME` in a discord channel. You need to edit the Messages.yml config. just a heads up, i wouldn't do the console since that posts alot of messages, I would attach a role to the start and stop.

**Comment by Scarsz** [comment]
Merging with #616
