### ISSUE TITLE
Feature: Ignore command and/or disable chat bridge messages

### ISSUE THREAD

**Issue by Weasel-Beans** [DiscordSRV/DiscordSRV#603]
Can there be a command for ignoring users across the chat bridge? Like users in minecraft ignoring discord messages, and/or the entire chat-bridge stream?

**Comment by Scarsz** [comment]
Existed at one point in time, was removed due to literally nobody using it and it not able to be implemented well with chat plugin implementations. Also makes the chat inconsistent with players replying to messages from Discord but not seeing the original message.

https://github.com/DiscordSRV/DiscordSRV/commit/135ad689a38cd20cd31c025a7a4c616a0607174b#diff-0ad22d382c20fe65fee64bbce9d8d345

**Comment by Vankka** [comment]
@Scarsz The request was for In-Game Players to be able to ignore specific Discord users

**Comment by Scarsz** [comment]
Point stands that it's not feasible to implement due to the chat plugin implementations not widely supporting such a thing
