### ISSUE TITLE
Suggestion: a scoreboard channel

### ISSUE THREAD

**Issue by Septikai** [DiscordSRV/DiscordSRV#777]
Would be cool if we could have a channel where you can view in game scoreboards without them being on the side of your screen In game, it wouldn't have to update constantly, just enough to keep it close to the reality. For example we have a scoreboard with around 20-30 people on the side of our screen, and we would like to put that in a discord channel instead so it doesn't take up half our screen.

**Comment by Vankka** [comment]
This wouldn't make sense to do since, scoreboards are usually personalized, that would most definetly require hooking to a lot of different scoreboard providing plugins to work, and I don't think this would solve the given use case, since the offical Discord client is bulky, and would be cumbersome to use on a single monitor with the Minecraft client
