### ISSUE TITLE
The BungeeChat API is shaded into the plugin

### ISSUE THREAD

**Issue by SydMontague** [DiscordSRV/DiscordSRV#869]
Since 1.20.0 the BungeeChat API is shaded into the plugin in it's regular package, I don't believe this is intentional and may cause conflicts.

**Comment by Vankka** [comment]
Fixed, available on dev builds https://snapshot.discordsrv.com

**Comment by rutgerkok** [comment]
Great that it's fixed, it's quite a hard issue to debug. On Minecraft 1.16, whenever any *other* plugin sends a message with a tooltip using the BungeeChat API, that player is disconnected. From the server, it seems like a normal disconnect: no stacktrace or anything. The client is sent to the dirt screen with a cryptic decoding error, see the screen below. Server admins will have a hard time figuring out what is going on, since the plugin sending the message with the tooltip seems to be at fault. So I'm hoping for a quick update to DiscordSRV, to save server admins some headaches. 😄 

![afbeelding](https://user-images.githubusercontent.com/1462188/95008446-369b5d00-061a-11eb-8499-4badd235010b.png)

**Comment by Vankka** [comment]
I've seen that before, amd didn't know what it is, ty for the info
