### ISSUE TITLE
Regional Voice Chat + Music Player (Suggestion)

### ISSUE THREAD

**Issue by Leo-Alexa** [DiscordSRV/DiscordSRV#885]
**Description**
This is an idea that I've had for a while but I've been thinking of the right words and explanation for the execution and implementation. The idea would be to have regional music playing on a lower volume on all the voice chat channels through the bot to create an ambient feel for the players based on location.

**Execution**
My idea would be that players who join the voice lobby, automatically get split out into a region channel where they are still muted and they would then get moved into voice channels as normal from these sub lobby channels. The bot could then play music in each of the sub lobby channels on a repeat based on a pre-defined track for each region in the settings.

**Expansion**
- This could potentially even be expanded so that there is an optional toggle to switch on region based music on/off in game and then this would mute the bot just for that user within discord.
- Potential options to alter volume in which they hear the music from the bot.
- You could also potentially set an option in which the voice chat is regional opposed to proximity so that players can talk to others based on the region they're in.

**Main Risks**
- This feature is heavily dependent on other plugins, most likely utilising WorldGuard to define regions in which to play music.
- Large development time to implement an overall relatively small feature.
- There is currently other web based alternatives that do this same functionality (opposed to inside Discord).

**Comment by Scarsz** [comment]
This would be simple enough to implement with (as you mentioned) WorldGuard flags, I have experience working with those so that wouldn't really be a challenge.

I don't really see DiscordSRV functioning as a music bot personally, it's just not really what the bot/plugin is about. That said, there's also the large limitation that the bot can only be in one voice channel of a given Discord server. In other words, the bot couldn't realistically be handling the music aspect of this anyway. Other bots would need to be involved to stream that in.

**Comment by Leo-Alexa** [comment]
Ah that makes sense. I'm still not fully familiar with the Discord API and it's limitations so I can completely appreciate that this wouldn't technically be possible without generating effectively dozens if not more bots for every instance of people coming into proximity of each other which really isn't viable.

Thanks for the quick reply anyway. :)
